from . import main_GAN_ensemble
from . import main_GAN_feature
from . import main_GAN_minmax
from . import main_ori
from . import main_Differential
from . import main_SMOTE 
from . import main_WG 
from . import main_test_real
from . import main_pure_GAN
from . import main_10fold